name: meins_image
version: '${project.version}'
main: de.dotEXE.image.Main
api-version: 1.19
depend: [ meins_core ]
authors: [ dotEXE ]
description: .
website: https://github.com/github-dotEXE

commands:
  image:
    description: /image -|[url]
